-- supabase/migrations/0001_create_reports_table.sql
-- 리포트 정보를 담을 reports 테이블 생성용 마이그레이션 파일입니다.
-- 이 파일은 국내 증시의 반도체, 피지컬 AI, 원자력 등 테마별/종목별 리서치 리포트 메타데이터를 저장합니다.

-- 1. reports 테이블 생성
CREATE TABLE IF NOT EXISTS public.reports (
    -- 고유 식별자 (자동 증가 정수형)
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 리포트 제목 (예: "반도체 업황 턴어라운드 전망")
    title TEXT NOT NULL,
    
    -- 분석 대상 종목명 (예: "삼성전자", "SK하이닉스")
    stock_name VARCHAR(100) NOT NULL,
    
    -- 리포트를 발행한 증권사 (예: "삼성을 비롯한 주요 증권사")
    brokerage VARCHAR(100) NOT NULL,
    
    -- 리포트 원본 PDF 또는 상세 페이지 URL 링크
    report_url TEXT NOT NULL,
    
    -- 테마 분류 (예: "반도체", "피지컬 AI", "원자력")
    theme VARCHAR(100) NOT NULL,
    
    -- 리포트가 실제로 발행된 날짜 (정렬 및 필터링 시 기준이 됨)
    published_at DATE NOT NULL,
    
    -- 데이터가 시스템에 수집되어 저장된 시각
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 2. 검색 성능 향상을 위한 인덱스(Index) 설정
-- 대시보드에서 테마별, 종목별로 필터링하거나 최신 발행일 순으로 정렬하는 쿼리가 자주 발생하므로 인덱스를 추가합니다.

-- 테마별 필터링용 인덱스
CREATE INDEX IF NOT EXISTS idx_reports_theme ON public.reports(theme);

-- 종목명 검색용 인덱스
CREATE INDEX IF NOT EXISTS idx_reports_stock_name ON public.reports(stock_name);

-- 최신순 정렬용 인덱스 (내림차순 정렬이 기본이므로 DESC 설정)
CREATE INDEX IF NOT EXISTS idx_reports_published_at ON public.reports(published_at DESC);

-- 3. Row Level Security (RLS) 설정 (보안 강화)
-- Supabase는 기본적으로 모든 테이블에 대해 RLS 설정을 활성화하여 무단 데이터 접근을 제어할 것을 권장합니다.
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- 누구나 대시보드에서 데이터를 조회(SELECT)할 수 있도록 허용하는 Read Policy 생성
CREATE POLICY "Allow public read access" 
ON public.reports 
FOR SELECT 
USING (true);

-- 데이터 삽입(INSERT), 수정(UPDATE), 삭제(DELETE)는 인증된 관리자 또는 서비스 내부 API를 통해서만 가능하도록 제한합니다.
-- (추후 Service Role Key 등을 이용해 크롤러가 직접 데이터를 적재할 때 사용 가능)
